"""init tables

Revision ID: 833aec2968b0
Revises: 
Create Date: 2026-08-05 12:04:40.146648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '833aec2968b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.String(length=100), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('owner_email', sa.String(length=255), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('shopify_shop_name', sa.String(length=255), nullable=True),
    sa.Column('shopify_access_token_enc', sa.Text(), nullable=True),
    sa.Column('shopify_webhook_secret_enc', sa.Text(), nullable=True),
    sa.Column('meta_access_token_enc', sa.Text(), nullable=True),
    sa.Column('meta_ad_account_id', sa.String(length=255), nullable=True),
    sa.Column('instagram_access_token_enc', sa.Text(), nullable=True),
    sa.Column('instagram_page_id', sa.String(length=255), nullable=True),
    sa.Column('brand_owner_whatsapp', sa.String(length=50), nullable=True),
    sa.Column('brand_owner_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_brand_id'), 'brands', ['brand_id'], unique=True)
    op.create_index(op.f('ix_brands_clerk_user_id'), 'brands', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_brands_owner_email'), 'brands', ['owner_email'], unique=True)
    op.create_table('chat_tool_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.String(length=255), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_tool_results_brand_id'), 'chat_tool_results', ['brand_id'], unique=False)
    op.create_index(op.f('ix_chat_tool_results_thread_id'), 'chat_tool_results', ['thread_id'], unique=False)
    op.create_table('agent_execution_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.String(length=100), nullable=False),
    sa.Column('agent', sa.String(length=100), nullable=False),
    sa.Column('task', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('tools_used', sa.JSON(), nullable=False),
    sa.Column('token_usage', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_execution_log_brand_id'), 'agent_execution_log', ['brand_id'], unique=False)
    op.create_table('agent_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.String(length=100), nullable=False),
    sa.Column('agent', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_memory_brand_id'), 'agent_memory', ['brand_id'], unique=False)
    op.create_table('audience_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.String(length=100), nullable=False),
    sa.Column('segment', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('campaign_success', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audience_segments_brand_id'), 'audience_segments', ['brand_id'], unique=False)
    op.create_table('content_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.String(length=100), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_plans_brand_id'), 'content_plans', ['brand_id'], unique=False)
    op.create_table('customer_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.String(length=100), nullable=False),
    sa.Column('segment', sa.String(length=50), nullable=False),
    sa.Column('customer_count', sa.Integer(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('customer_ids', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'segment', name='uq_segment_brand_name')
    )
    op.create_index(op.f('ix_customer_segments_brand_id'), 'customer_segments', ['brand_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.String(length=100), nullable=False),
    sa.Column('shopify_customer_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('orders_count', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Float(), nullable=False),
    sa.Column('first_order_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_order_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'shopify_customer_id', name='uq_customers_brand_shopify_id')
    )
    op.create_index(op.f('ix_customers_brand_id'), 'customers', ['brand_id'], unique=False)
    op.create_table('inventory_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_alerts_brand_id'), 'inventory_alerts', ['brand_id'], unique=False)
    op.create_table('inventory_forecasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.String(length=100), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('forecast_days', sa.Integer(), nullable=False),
    sa.Column('predicted_units_sold', sa.Float(), nullable=False),
    sa.Column('predicted_stock_remaining', sa.Float(), nullable=False),
    sa.Column('days_until_stockout', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_forecasts_brand_id'), 'inventory_forecasts', ['brand_id'], unique=False)
    op.create_index(op.f('ix_inventory_forecasts_sku'), 'inventory_forecasts', ['sku'], unique=False)
    op.create_table('marketing_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('target_audience', sa.String(length=255), nullable=False),
    sa.Column('budget', sa.String(length=100), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('meta_campaign_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketing_campaigns_brand_id'), 'marketing_campaigns', ['brand_id'], unique=False)
    op.create_table('marketing_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.String(length=100), nullable=False),
    sa.Column('insight', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketing_insights_brand_id'), 'marketing_insights', ['brand_id'], unique=False)
    op.create_table('policy_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.String(length=100), nullable=False),
    sa.Column('agent', sa.String(length=50), server_default='inventory', nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_documents_brand_id'), 'policy_documents', ['brand_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.String(length=100), nullable=False),
    sa.Column('shopify_product_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'shopify_product_id', name='uq_products_brand_shopify_id')
    )
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_table('returns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.String(length=100), nullable=False),
    sa.Column('shopify_order_id', sa.BigInteger(), nullable=False),
    sa.Column('shopify_refund_id', sa.BigInteger(), nullable=False),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('refund_amount', sa.Float(), nullable=False),
    sa.Column('restock', sa.Boolean(), nullable=False),
    sa.Column('return_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_returns_brand_id'), 'returns', ['brand_id'], unique=False)
    op.create_table('sales_anomalies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.String(length=100), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('expected', sa.Float(), nullable=False),
    sa.Column('actual', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_anomalies_brand_id'), 'sales_anomalies', ['brand_id'], unique=False)
    op.create_table('sales_forecasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.String(length=100), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('predicted_revenue', sa.Float(), nullable=False),
    sa.Column('predicted_orders', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_forecasts_brand_id'), 'sales_forecasts', ['brand_id'], unique=False)
    op.create_table('sales_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_insights_brand_id'), 'sales_insights', ['brand_id'], unique=False)
    op.create_table('sales_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.String(length=100), nullable=False),
    sa.Column('shopify_order_id', sa.BigInteger(), nullable=False),
    sa.Column('shopify_customer_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('financial_status', sa.String(length=50), nullable=True),
    sa.Column('fulfillment_status', sa.String(length=50), nullable=True),
    sa.Column('subtotal_price', sa.Float(), nullable=False),
    sa.Column('total_discounts', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('discount_codes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'shopify_order_id', name='uq_orders_brand_shopify_id')
    )
    op.create_index(op.f('ix_sales_orders_brand_id'), 'sales_orders', ['brand_id'], unique=False)
    op.create_index(op.f('ix_sales_orders_created_at'), 'sales_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_sales_orders_shopify_customer_id'), 'sales_orders', ['shopify_customer_id'], unique=False)
    op.create_table('sales_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.String(length=100), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('kpis', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_reports_brand_id'), 'sales_reports', ['brand_id'], unique=False)
    op.create_table('seasonal_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('expected_demand_multiplier', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_whatsapp', sa.String(length=50), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('minimum_order_qty', sa.Integer(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_brand_id'), 'suppliers', ['brand_id'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('current_utilization', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_brand_id'), 'warehouses', ['brand_id'], unique=False)
    op.create_table('order_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.String(length=100), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('shopify_line_item_id', sa.BigInteger(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('variant_id', sa.BigInteger(), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_line_items_brand_id'), 'order_line_items', ['brand_id'], unique=False)
    op.create_index(op.f('ix_order_line_items_order_id'), 'order_line_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_line_items_sku'), 'order_line_items', ['sku'], unique=False)
    op.create_table('product_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('shopify_variant_id', sa.BigInteger(), nullable=False),
    sa.Column('inventory_item_id', sa.BigInteger(), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('compare_at_price', sa.Float(), nullable=True),
    sa.Column('inventory_quantity', sa.Integer(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'sku', name='uq_variants_brand_sku')
    )
    op.create_index(op.f('ix_product_variants_brand_id'), 'product_variants', ['brand_id'], unique=False)
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.String(length=100), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=False),
    sa.Column('ordered_quantity', sa.Integer(), nullable=False),
    sa.Column('expected_delivery', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_brand_id'), 'purchase_orders', ['brand_id'], unique=False)
    op.create_table('scheduled_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.String(length=100), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('published_ref_id', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['marketing_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_content_brand_id'), 'scheduled_content', ['brand_id'], unique=False)
    op.create_table('content_performance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.String(length=100), nullable=False),
    sa.Column('scheduled_content_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('engagement', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=False),
    sa.Column('conversion', sa.Float(), nullable=False),
    sa.Column('roas', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.ForeignKeyConstraint(['scheduled_content_id'], ['scheduled_content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_performance_brand_id'), 'content_performance', ['brand_id'], unique=False)
    op.create_table('reorder_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.String(length=100), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('supplier_message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reorder_recommendations_brand_id'), 'reorder_recommendations', ['brand_id'], unique=False)
    op.create_index(op.f('ix_reorder_recommendations_sku'), 'reorder_recommendations', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reorder_recommendations_sku'), table_name='reorder_recommendations')
    op.drop_index(op.f('ix_reorder_recommendations_brand_id'), table_name='reorder_recommendations')
    op.drop_table('reorder_recommendations')
    op.drop_index(op.f('ix_content_performance_brand_id'), table_name='content_performance')
    op.drop_table('content_performance')
    op.drop_index(op.f('ix_scheduled_content_brand_id'), table_name='scheduled_content')
    op.drop_table('scheduled_content')
    op.drop_index(op.f('ix_purchase_orders_brand_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_brand_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_order_line_items_sku'), table_name='order_line_items')
    op.drop_index(op.f('ix_order_line_items_order_id'), table_name='order_line_items')
    op.drop_index(op.f('ix_order_line_items_brand_id'), table_name='order_line_items')
    op.drop_table('order_line_items')
    op.drop_index(op.f('ix_warehouses_brand_id'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_suppliers_brand_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_table('seasonal_events')
    op.drop_index(op.f('ix_sales_reports_brand_id'), table_name='sales_reports')
    op.drop_table('sales_reports')
    op.drop_index(op.f('ix_sales_orders_shopify_customer_id'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_created_at'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_brand_id'), table_name='sales_orders')
    op.drop_table('sales_orders')
    op.drop_index(op.f('ix_sales_insights_brand_id'), table_name='sales_insights')
    op.drop_table('sales_insights')
    op.drop_index(op.f('ix_sales_forecasts_brand_id'), table_name='sales_forecasts')
    op.drop_table('sales_forecasts')
    op.drop_index(op.f('ix_sales_anomalies_brand_id'), table_name='sales_anomalies')
    op.drop_table('sales_anomalies')
    op.drop_index(op.f('ix_returns_brand_id'), table_name='returns')
    op.drop_table('returns')
    op.drop_index(op.f('ix_products_brand_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_policy_documents_brand_id'), table_name='policy_documents')
    op.drop_table('policy_documents')
    op.drop_index(op.f('ix_marketing_insights_brand_id'), table_name='marketing_insights')
    op.drop_table('marketing_insights')
    op.drop_index(op.f('ix_marketing_campaigns_brand_id'), table_name='marketing_campaigns')
    op.drop_table('marketing_campaigns')
    op.drop_index(op.f('ix_inventory_forecasts_sku'), table_name='inventory_forecasts')
    op.drop_index(op.f('ix_inventory_forecasts_brand_id'), table_name='inventory_forecasts')
    op.drop_table('inventory_forecasts')
    op.drop_index(op.f('ix_inventory_alerts_brand_id'), table_name='inventory_alerts')
    op.drop_table('inventory_alerts')
    op.drop_index(op.f('ix_customers_brand_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_customer_segments_brand_id'), table_name='customer_segments')
    op.drop_table('customer_segments')
    op.drop_index(op.f('ix_content_plans_brand_id'), table_name='content_plans')
    op.drop_table('content_plans')
    op.drop_index(op.f('ix_audience_segments_brand_id'), table_name='audience_segments')
    op.drop_table('audience_segments')
    op.drop_index(op.f('ix_agent_memory_brand_id'), table_name='agent_memory')
    op.drop_table('agent_memory')
    op.drop_index(op.f('ix_agent_execution_log_brand_id'), table_name='agent_execution_log')
    op.drop_table('agent_execution_log')
    op.drop_index(op.f('ix_chat_tool_results_thread_id'), table_name='chat_tool_results')
    op.drop_index(op.f('ix_chat_tool_results_brand_id'), table_name='chat_tool_results')
    op.drop_table('chat_tool_results')
    op.drop_index(op.f('ix_brands_owner_email'), table_name='brands')
    op.drop_index(op.f('ix_brands_clerk_user_id'), table_name='brands')
    op.drop_index(op.f('ix_brands_brand_id'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
